project_id = "ivkafpxtszrdgzabxjsg"

[functions.analyze-symptoms]
verify_jwt = false

[functions.health-coach]
verify_jwt = true

[functions.mental-health-coach]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = true

[functions.text-to-voice]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.generate-insights]
verify_jwt = true