// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivkafpxtszrdgzabxjsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2a2FmcHh0c3pyZGd6YWJ4anNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDI2OTAsImV4cCI6MjA2OTQ3ODY5MH0.o0LphBdQdoIsE7bld_8RO8OCCRCzCXxZ3A8zHxJCM9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});